baseURL = "https://mh9.codes/"
languageCode = "en"
title = "mh9 codes"
theme = "anatole"
summarylength = 80
enableEmoji = true
enableRobotsTXT = true
disqusShortname = "mh9codes"
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true

[params]
author = "Michael Hausenblas"
description = "Sharing good practices around cloud native development and operations"
copyright = "2019-2021"
profilePicture = "images/mhausenblas.png"
displayMode = "dark"

  [[params.socialIcons]]
  icon = "fa-github"
  title = "GitHub"
  url = "https://github.com/mhausenblas"

  [[params.socialIcons]]
  icon = "fa-twitter"
  title = "Tiwtter"
  url = "https://twitter.com/mhausenblas"

  [[params.socialIcons]]
  icon = "fa-envelope"
  title = "e-mail"
  url = "mailto:mh9@o11y.engineering"

[menu]

  [[menu.main]]
  name = "Home"
  weight = 100
  url = "/"

  [[menu.main]]
  name = "Archive"
  weight = 200
  identifier = "posts"
  url = "/posts/"

  [[menu.main]]
  name = "About"
  weight = 300
  url = "/about"
