baseURL = "https://mh9.codes/"
languageCode = "en-us"
title = "mh9 codes"
theme = "cactus-plus"
disqusShortname = "mh9codes"
enableDisqus = true

[params]
github_username = "mhausenblas"
twitter_username = "mhausenblas"
iconFont = "mono-social"
